@baseURL = http://localhost:3000

### Test API
GET {{baseURL}}/health
Content-Type: application/json

### Characters
### Find All
GET  {{baseURL}}/api/v1/characters?limit=10
Content-Type: application/json

### Find By Name
GET  {{baseURL}}/api/v1/characters?name=gojo

### Find By Id
GET  {{baseURL}}/api/v1/characters/2